# Generated by Django 6.0 on 2026-01-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
